#!/usr/bin/env bash
# This is a Bash script that displays:
# The content of the current directory in a list format
# Where only the part of the name after the first dash is displayed
for i in $ls *;
do echo "$i" | cut -d '-' -f2
done
